# ComfyUI Asset Generation Specification
# Defines assets to generate for the character customization system

version: "1.0.0"
output_dir: "../frontend/public/assets/characters"
manifest_output: "../frontend/public/assets/characters/asset_manifest.json"

# Pipeline configurations for advanced character generation
pipelines:
  character_full:
    workflow: "character_7layer_pipeline.json"
    layers: 7
    output_stages:
      - sketch
      - lineart
      - flat_color
      - shaded
      - detailed
      - effects
      - final
    cache_intermediates: true
    
  poses_sheet:
    workflow: "poses_sheet.json"
    poses:
      - idle
      - combat_violence
      - casting_revelation
      - commanding_influence
      - injured
      - maimed
      - victory
      - dead
      - back_view
    grid_layout: "3x3"
    output_size: "2048x2048"
    
  outfits_sheet:
    workflow: "outfits_sheet.json"
    outfit_categories:
      - cultivation_basic
      - cultivation_ornate
      - combat_armor
      - casual
      - formal
      - damaged
    grid_layout: "2x3"
    output_size: "1536x2048"

  character_sheet:
    workflow: "character_sheet_full.json"
    sections:
      portrait:
        size: "512x768"
        position: "left"
      poses:
        size: "768x512"
        position: "right-top"
      outfits:
        size: "768x512"
        position: "right-bottom"
      stats_zone:
        size: "256x768"
        position: "far-right"
        transparent: true

# TTRPG pillar effect mappings
pillar_effects:
  violence:
    aura_color: "#FF4444"
    effect_type: "flame_sparks"
    intensity_multiplier: 0.1  # per SCL
    prompt_addition: "red flame aura, fiery energy, combat qi, martial power emanating"
  influence:
    aura_color: "#4444FF"
    effect_type: "ethereal_glow"
    intensity_multiplier: 0.1
    prompt_addition: "blue ethereal glow, commanding presence, social qi, spiritual authority"
  revelation:
    aura_color: "#44FF44"
    effect_type: "mystical_symbols"
    intensity_multiplier: 0.1
    prompt_addition: "green mystical symbols, enlightened aura, insight qi, arcane knowledge"

# Face consistency settings
face_transposition:
  embedding_format: "insightface"
  storage_path: "embeddings/"
  similarity_threshold: 0.6
  workflow: "face_swap.json"

# Base models
base_models:
  - id: "female"
    name: "Female Base"
    workflow: "base_character.json"
    prompt_template: "prompts/female_base.txt"
    output_filename: "bases/female_base_neutral.png"
    dimensions:
      width: 512
      height: 768
    seed: 42
    negative_prompt: "blurry, low quality, watermark, extra limbs, distorted, ugly"

  - id: "male"
    name: "Male Base"
    workflow: "base_character.json"
    prompt_template: "prompts/male_base.txt"
    output_filename: "bases/male_base_neutral.png"
    dimensions:
      width: 512
      height: 768
    seed: 43
    negative_prompt: "blurry, low quality, watermark, extra limbs, distorted, ugly"

# Overlay categories
categories:
  - id: "hair"
    name: "Hair Style"
    description: "Traditional and modern hairstyles"
    workflow: "overlay_layer.json"
    options:
      - id: "hair-001"
        name: "Long Flowing"
        layers:
          - type: "hair_back"
            prompt_template: "prompts/hair/long_flowing_back.txt"
            output_filename: "overlays/hair/hair-001-back.png"
            seed: 1001
          - type: "hair_front"
            prompt_template: "prompts/hair/long_flowing_front.txt"
            output_filename: "overlays/hair/hair-001-front.png"
            seed: 1002
        thumbnail_output: "overlays/hair/hair-001-thumb.png"

      - id: "hair-002"
        name: "Topknot Bun"
        layers:
          - type: "hair_back"
            prompt_template: "prompts/hair/topknot_back.txt"
            output_filename: "overlays/hair/hair-002-back.png"
            seed: 1003
          - type: "hair_front"
            prompt_template: "prompts/hair/topknot_front.txt"
            output_filename: "overlays/hair/hair-002-front.png"
            seed: 1004
        thumbnail_output: "overlays/hair/hair-002-thumb.png"

      - id: "hair-003"
        name: "Half Up Half Down"
        layers:
          - type: "hair_back"
            prompt_template: "prompts/hair/half_up_back.txt"
            output_filename: "overlays/hair/hair-003-back.png"
            seed: 1005
          - type: "hair_front"
            prompt_template: "prompts/hair/half_up_front.txt"
            output_filename: "overlays/hair/hair-003-front.png"
            seed: 1006
        thumbnail_output: "overlays/hair/hair-003-thumb.png"

      - id: "hair-004"
        name: "Braided Crown"
        layers:
          - type: "hair_back"
            prompt_template: "prompts/hair/braided_back.txt"
            output_filename: "overlays/hair/hair-004-back.png"
            seed: 1007
          - type: "hair_front"
            prompt_template: "prompts/hair/braided_front.txt"
            output_filename: "overlays/hair/hair-004-front.png"
            seed: 1008
        thumbnail_output: "overlays/hair/hair-004-thumb.png"

      - id: "hair-005"
        name: "Short Warrior"
        layers:
          - type: "hair_back"
            prompt_template: "prompts/hair/short_back.txt"
            output_filename: "overlays/hair/hair-005-back.png"
            seed: 1009
          - type: "hair_front"
            prompt_template: "prompts/hair/short_front.txt"
            output_filename: "overlays/hair/hair-005-front.png"
            seed: 1010
        thumbnail_output: "overlays/hair/hair-005-thumb.png"

  - id: "eyes"
    name: "Eye Shape"
    description: "Various eye shapes and expressions"
    workflow: "overlay_layer.json"
    options:
      - id: "eyes-001"
        name: "Calm Almond"
        layers:
          - type: "eyes"
            prompt_template: "prompts/eyes/calm_almond.txt"
            output_filename: "overlays/eyes/eyes-001.png"
            seed: 2001
        thumbnail_output: "overlays/eyes/eyes-001-thumb.png"

      - id: "eyes-002"
        name: "Sharp Phoenix"
        layers:
          - type: "eyes"
            prompt_template: "prompts/eyes/sharp_phoenix.txt"
            output_filename: "overlays/eyes/eyes-002.png"
            seed: 2002
        thumbnail_output: "overlays/eyes/eyes-002-thumb.png"

      - id: "eyes-003"
        name: "Wide Round"
        layers:
          - type: "eyes"
            prompt_template: "prompts/eyes/wide_round.txt"
            output_filename: "overlays/eyes/eyes-003.png"
            seed: 2003
        thumbnail_output: "overlays/eyes/eyes-003-thumb.png"

      - id: "eyes-004"
        name: "Narrow Focused"
        layers:
          - type: "eyes"
            prompt_template: "prompts/eyes/narrow_focused.txt"
            output_filename: "overlays/eyes/eyes-004.png"
            seed: 2004
        thumbnail_output: "overlays/eyes/eyes-004-thumb.png"

      - id: "eyes-005"
        name: "Gentle Crescent"
        layers:
          - type: "eyes"
            prompt_template: "prompts/eyes/gentle_crescent.txt"
            output_filename: "overlays/eyes/eyes-005.png"
            seed: 2005
        thumbnail_output: "overlays/eyes/eyes-005-thumb.png"

# Style settings - Romance of Three Kingdoms / KOEI Tecmo Inspired
style:
  base_style: "Romance of Three Kingdoms game art, KOEI Tecmo style, Dynasty Warriors aesthetic, semi-realistic anime, Yuto Sano inspired, painterly soft gradients, luminous rim lighting, Han dynasty aesthetic, wuxia fantasy, manhwa, chinese period art inspired, ink wash painting"
  quality_tags: "masterpiece, best quality, highly detailed, professional game illustration, AAA game character art, 8k, cinematic lighting"
  negative_base: "blurry, low quality, watermark, text, signature, distorted anatomy, western cartoon, chibi, super deformed, amateur, ugly"
  
  # Reference style notes from Romance of Three Kingdoms visual inspiration:
  # - Character portraits: Large detailed busts on screen edges, ornate armor/robes
  # - Combat UI: Damage numbers in styled blue bubbles, stat bars with ATK/DEF/INT/STR
  # - Location icons: Bronze/gold circular icons with Chinese-style symbols
  # - Top HUD: Resource displays with Chinese characters, date/season indicators
  # - Navigation: Ornate gilded buttons with category icons
  reference_elements:
    character_portraits:
      style: "large detailed bust portrait, facing 3/4 view, ornate armor or robes, dramatic lighting, clean background gradient"
      placement: "left or right screen edge, approximately 1/4 screen width"
      examples: "Guan Yu, Cao Cao, Zhuge Liang style portraits"
    combat_hud:
      damage_numbers: "blue elliptical bubbles, white bold text, slight glow"
      stat_bars: "horizontal yellow/red bars, ATK/INT/STR/DEF labels"
      combo_indicators: "linked portrait icons, damage multiplier badges"
    location_icons:
      style: "bronze/gold circular medallions, Chinese character or symbol center, ornate rim"
      categories: "Farmland, Market, Workshop, Tavern, Palace, Castle Gates, Garrison, Home"
    navigation_buttons:
      style: "gilded ornate frames, gradient backgrounds, icon + text labels"
      examples: "Personnel, Military, Plots, Diplomacy, Policy, Espionage"

# ComfyUI server settings (overridable via environment variables)
comfyui:
  url: "http://127.0.0.1:8188"
  timeout: 300
  polling_interval: 2
  use_websocket: true
